sudo: required

services:
  - docker

script:
  # setup QEMU
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # build images
  - docker build --build-arg SERVICE=$SERVICE --build-arg PORT=$PORT -t nginx:$DOCKER_TAG -f Dockerfile.$DOCKER_ARCH .
  # push images
  - docker login -u="$DOCKER_HUB_LOGIN" -p="$DOCKER_HUB_PASSWORD"
  - docker tag nginx:$DOCKER_TAG allandequeiroz/nginx:$DOCKER_TAG
  - docker push allandequeiroz/nginx:$DOCKER_TAG
  - >
    if [ "$LATEST" == "true" ]; then
      docker tag nginx:$DOCKER_TAG allandequeiroz/nginx:latest
      docker push allandequeiroz/nginx:latest
    fi

env:
  matrix:
    - DOCKER_TAG=ghost-arm64    DOCKER_ARCH=arm64   SERVICE=ghost   PORT=2368
    - DOCKER_TAG=ghost-amd64    DOCKER_ARCH=amd64   SERVICE=ghost   PORT=2368     LATEST=true
    - DOCKER_TAG=wiki-arm64     DOCKER_ARCH=arm64   SERVICE=wiki    PORT=8080
    - DOCKER_TAG=wiki-amd64     DOCKER_ARCH=amd64   SERVICE=wiki    PORT=8080
