sudo: required

services:
- docker

git:
  depth: false

script:
# setup QEMU
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build images
- docker build -t nginx:$DOCKER_TAG -f Dockerfile.$DOCKER_ARCH .
- docker login -u="$DOCKER_HUB_LOGIN" -p="$DOCKER_HUB_PASSWORD"
- docker tag nginx:$DOCKER_TAG allandequeiroz/nginx:$DOCKER_TAG
- docker push allandequeiroz/nginx:$DOCKER_TAG
- >
  if [ "$LATEST" == "true" ]; then
    docker tag nginx:$DOCKER_TAG allandequeiroz/nginx:latest
    docker push allandequeiroz/nginx:latest
  fi
env:
  matrix:
  - DOCKER_TAG=arm64     DOCKER_ARCH=arm64       LATEST=true
  - DOCKER_TAG=amd64     DOCKER_ARCH=amd64