version: '3.2'

services:

  # NGinx as a Ghost proxy    
  nginx:
    image: allandequeiroz/nginx:latest
    ports:
      - mode: host
        target: 443
        published: 443
      - mode: host
        target: 80
        published: 80
